// Generated by typings
// Source: https://raw.githubusercontent.com/andrew-w-ross/typings-youtube-api-search/master/youtube-api-search.d.ts
declare namespace YTSearch {
	interface ISearchArgs {
		key: string;
		term?: string;
	}

	interface IVideoResponse {
		kind: string;
		etag: string;
		nextPageToken: string;
		regionCode: string;
		pageInfo: IVideoPageInfo;
		items: IVideoItem[];
	}

	interface IVideoItem {
		etag: string;
		id: IVideoId;
		kind: string;
		snippet: IVideoSnippet;
	}

	interface IVideoId {
		kind:string;
		videoId:string;	
	}

	interface IVideoSnippet {
		channelId: string;
		channelTitle: string;
		description: string;
		liveBroadcastContent: string;
		publishedAt: string;
		thumbnails: IVideoThumbnails;
		title: string;
	}

	interface IVideoPageInfo {
		totalResults: number;
		resultsPerPage: number;
	}

	interface IVideoThumbnails {
		default: IThumbnail;
		high: IThumbnail;
		medium: IThumbnail;
	}

	interface IThumbnail {
		url: string;
		width: number;
		height: number;
	}

	interface ISearch {
		(searchArgs: ISearchArgs, callback: (data: IVideoItem[]) => any): void;
	}
}

declare module "youtube-api-search"{
	let ytSearch : YTSearch.ISearch;
	export = ytSearch;	
}
